name: Hunt's blog
description: 伤情处，高城望断，灯火已黄昏…
url: http://huntxu.github.io

timezone: Asia/Hong_Kong

paginate: 10
paginate_path: "page:num"

permalink: /:year-:month-:day-:title.html

markdown: redcarpet

redcarpet:
    extensions: [
        'no_intra_emphasis', 'tables', 'space_after_headers', 'autolink',
        'strikethrough', 'superscript'
    ]
